name: momentum
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6
  - gensim
  - ipython
  - joblib
  - jupyter
  - pip
  - matplotlib
  - numpy
  - pymc3=3.7
  - scikit-learn
  - scipy=1.3.2
  - statsmodels
  - tqdm
  - pip:
    - jax==0.1.57
    - jaxlib==0.1.37
    - arviz==0.6.1
    - cython
    - numpyro==0.2.4
    - numba==0.47.0
    - pdbpp
    - sacred==0.7.4
